### ISSUE TITLE
Replace with NA where required

### ISSUE THREAD

**Issue by tauseefsshah** [cbgaindia/district-dashboard#52]
On district dashboard, various heads in demographic highlights is zero. For Example: Shamli (UP) (that is mentioned below). Even in, Ayodhya, Area (Sq. Km.) is also mentioned in zero on district dashboard. In the data shared, some entries were ‘NA’. Might be good to have NA wherever feasible.

Reported by Suraj Jaiswal

**Comment by samwhocodes** [comment]
<img width="1318" alt="Screenshot 2023-02-27 at 1 20 02 PM" src="https://user-images.githubusercontent.com/67921422/221509753-8e0328db-f57b-43af-ba30-01d71ef95c1a.png">


The data has the value NA but it is still showing 0 in the front end.

**Comment by tauseefsshah** [comment]
It's a quick hack for now. Code needs to be refactor in frontend. @aashimgarg
