### ISSUE TITLE
Application Error on District Dashboard

### ISSUE THREAD

**Issue by samwhocodes** [cbgaindia/district-dashboard#55]
<img width="1429" alt="Screenshot 2023-03-23 at 2 13 27 AM" src="https://user-images.githubusercontent.com/67921422/227033989-084be668-3c25-460f-acdd-71516a1e32df.png">

This is happening when I am clicking explore on SBM-U and then trying to compare districts.

**Comment by PixeledCode** [comment]
@aashimgarg please look into it

**Comment by aashimgarg** [comment]
Hey @samwhocodes can you exact url for which you are getting this application error

**Comment by samwhocodes** [comment]
@aashimgarg sending the link might not work (https://district.openbudgetsindia.org/bihar/188?scheme=sbmu&indicator=budget-utilisation)
Go to any state, and open any district, on the scheme performance page go and click on explore more fo SBM-U. Then on the compare district page, in the dropdown no other district is being listed and if I type anything it automatically going to the application error page.

**Comment by aashimgarg** [comment]
> @aashimgarg sending the link might not work (https://district.openbudgetsindia.org/bihar/188?scheme=sbmu&indicator=budget-utilisation) Go to any state, and open any district, on the scheme performance page go and click on explore more fo SBM-U. Then on the compare district page, in the dropdown no other district is being listed and if I type anything it automatically going to the application error page.

Thanks for the information, working on it!

**Comment by samwhocodes** [comment]
Done
